project2/webapps/grading/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :instructors 
  resources :courses
  resources :students

  end

project2/webapps/grading/app/models/course.rb
class Course < ActiveRecord::Base
end

project2/webapps/grading/app/models/instructor.rb
class Instructor < ActiveRecord::Base
end

project2/webapps/grading/app/models/student.rb
class Student < ActiveRecord::Base
end

project2/webapps/grading/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

project2/webapps/grading/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
end

project2/webapps/grading/app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @instructors = Instructor.all
  end
 
  def show
    @instructor = Instructor.find(params[:id])
  end
 
  def new
    @instructor = Instructor.new
  end
 
  def edit
    @instructor = Instructor.find(params[:id])
  end
 
  def create
    @instructor = Instructor.new(instructor_params)
 
    if @instructor.save
      redirect_to @instructor
    else
      render 'new'
    end
  end
 
  def update
    @instructor = Instructor.find(params[:id])

    :courses
    split(:courses)
    for each string-course
	Course.find(string-course)
	
    if @instructor.update(instructor_params)
      redirect_to @instructor
    else
      render 'edit'
    end
  end
 
  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
 
    redirect_to instructors_path
  end
 
  private
    def instructor_params
      params.require(:instructor).permit(:name, :office, :webpage)
    end
end

project2/webapps/grading/app/controllers/students_controller.rb
class StudentsController < ApplicationController
end

project2/webapps/grading/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

project2/webapps/grading/app/helpers/application_helper.rb
module ApplicationHelper
end

project2/webapps/grading/app/helpers/courses_helper.rb
module CoursesHelper
end

project2/webapps/grading/app/helpers/instructors_helper.rb
module InstructorsHelper
end

project2/webapps/grading/app/helpers/students_helper.rb
module StudentsHelper
end

project2/webapps/grading/app/helpers/welcome_helper.rb
module WelcomeHelper
end

project2/webapps/grading/app/views/courses/index.html.erb
Use app/views/instructors/index.html.erb as a template to create a similar page for courses.

project2/webapps/grading/app/views/courses/new.html.erb
Use app/views/instructors/new.html.erb as a template to create a similar page for courses (including error detection)

project2/webapps/grading/app/views/courses/show.html.erb
<p>
<strong>Title:</strong>
<%= @course.title %>
</p>

<p>
<strong>Description:</strong>
<%= @course.description %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

project2/webapps/grading/app/views/instructors/edit.html.erb
<h1>Editing article</h1>

<%= form_for :instructor, url: instructor_path(@instructor), method: :patch do |f| %>
 
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2>
	<%= pluralize(@instructor.errors.count, "error") %> prohibited
	this instructor from being saved:
      </h2>
      <ul>
	<% @instructor.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :office %><br>
    <%= f.text_area :office %>
  </p>

  <p>
    <%= f.label :webpage %><br>
    <%= f.text_area :webpage %>
  </p>
 
  <p>
    <%= f.label :courses %><br>
    <%= f.text_area :courses %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', instructors_path %>

project2/webapps/grading/app/views/instructors/index.html.erb
<h1>Listing Instructors</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Office</th>
    <th>Webpage</th>
    <th colspan="2"></th>
  </tr>
 
  <% @instructors.each do |instructor| %>
    <tr>
      <td><%= instructor.name %></td>
      <td><%= instructor.office %></td>
      <td><%= instructor.webpage %></td>
      <td><%= link_to 'Show', instructor_path(instructor) %></td>
      <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
      <td><%= link_to 'Destroy', instructor_path(instructor),
                    method: :delete,
		    data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Create new instructor', new_instructor_path %> <br>

project2/webapps/grading/app/views/instructors/new.html.erb
<%= form_for :instructor, url: instructors_path do |f| %>
 
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2>
	<%= pluralize(@instructor.errors.count, "error") %> prohibited
	this instructor from being saved:
      </h2>
      <ul>
	<% @instructor.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :office %><br>
    <%= f.text_area :office %>
  </p>

  <p>
    <%= f.label :webpage %><br>
    <%= f.text_area :webpage %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', instructors_path %>

project2/webapps/grading/app/views/instructors/show.html.erb
<p>
<strong>Name:</strong>
<%= @instructor.name %>
</p>

<p>
<strong>Department:</strong>
<%= @instructor.office %>
</p>

<p>
<strong>Webpage:</strong>
<%= @instructor.webpage %>
</p>

The information about assignments available for grading should appear here. <br><br>

A link to creating an assignment should also appear here. <br><br>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>

project2/webapps/grading/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grading</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

project2/webapps/grading/app/views/students/index.html.erb
Use app/views/instructors/index.html.erb as a template to create a similar page for students.

project2/webapps/grading/app/views/students/new.html.erb
Use app/views/instructors/new.html.erb as a template to create a similar page for students (including error detection).

project2/webapps/grading/app/views/students/show.html.erb
<p>
<strong>Name:</strong>
<%= @student.name %>
</p>

<p>
<strong>Address:</strong>
<%= @student.address %>
</p>

<h3> Available Assignments </h3>
The information about assignments available for submitting (or editing) should appear here.

<h3> Scores for Submitted Assignments </h3>
The information about grades for completed assignments should appear here.

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

project2/webapps/grading/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Instructors', controller: 'instructors' %><br><br>
<%= link_to 'Students', controller: 'students' %><br><br>
<%= link_to 'Courses', controller: 'courses' %>